name: test

on:
  push:
    branches:
      - action
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
          npm run build
        env:
          NPM_REGISTRY: https://registry.npmjs.org/
      - name: Run test
        run: |
          npm run test
